[workspace]
members = ["day01", "day02", "util"]
resolver = "2"

[package]
name = "advent_of_code_2024"
edition = "2021"

[dependencies]
day01 = {path = "day01"}
day02 = {path = "day02"}
util = {path = "util"}